name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [node18-linux-x64, node18-macos-x64]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: npm install -g pkg
      - run: npm install
      - run: npm run build
      - run: pkg . --targets ${{ matrix.target }} --output client/open-bore-${{ matrix.target }}
      - name: Rename binaries
        run: |
          mv client/open-bore-${{ matrix.target }} client/open-bore-${{ matrix.target == 'node18-linux-x64' && 'linux' || 'macos' }}
      - uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: client/open-bore-*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: binaries
          path: client/
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            client/open-bore-linux
            client/open-bore-macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}